services:
  mongodb_test:
    image: mongo:latest
    restart: always
    container_name: mongodb_test
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/etc/mongo
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    env_file:
      - .env

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local